spring:
  data:
    mongodb:
      uri: mongodb+srv://yaoyiming00116:Yym980522@cluster0.6oy4wvd.mongodb.net/?retryWrites=true&w=majority
      database: GroupProject
  mvc:
    servlet:
      path: /employee
  application:
    name: employee-service

server:
  port: 8089

s3:
  file-path-prefix: http://localhost:8084/s3/download/

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: javaTraining

