spring:
  application:
    name: onboarding-service
  mvc:
    servlet:
      path: /onboarding

security:
  jwt:
    token:
      key: javaTraining


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8094

s3:
  file-path-prefix: http://localhost:8084/s3/download/

