cloud:
  aws:
    credentials:
      access-key: AKIAW2GGYHHFT3WGD6C6
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: ivanyou-bucket-demo

server:
  port: 8084

spring:
  application:
    name: s3-service
  mvc:
    servlet:
      path: /s3


  servlet:
    multipart:
      max-file-size: 10MB

  spring:
    servlet:
      multipart:
        max-request-size: 10MB

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: javaTraining
