spring:
  application:
    name: application-core-service
  mvc:
    servlet:
      path: /application-core-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka