spring:
  mvc:
    servlet:
      path: /housing
  application:
    name: housing-service

server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: javaTraining
